import type { Metadata } from "next";
import { Geist, Geist_Mono, Tektur } from "next/font/google";
import { Provider } from "./provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tektur = Tektur({
  variable: "--font-tektur",
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Devrary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="black" />
          <meta name="apple-mobile-web-app-title" content="My App" />
          <link rel="apple-touch-icon" href="/logo.png" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${tektur.variable} antialiased`}
        >
          <Provider>{children}</Provider>
      </body>
    </html>
  );
}